[package]
name = "balatro-mod-manager"
version = "0.1.0"
description = "A mod manager for Balatro - easily install and manage mods for the popular roguelike deckbuilding game"
authors = ["skyline69<67526259+skyline69@users.noreply.github.com>"]
edition = "2021"
keywords = ["gaming", "mods", "balatro", "manager", "tauri"]
categories = ["games", "development-tools", "gui"]
readme = "README.md"
repository = "https://github.com/skyline69/balatro-mod-manager"


[lib]
name = "balatro_mod_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2"
bmm-lib = { path = "bmm-lib" }
lovely-unix = { path = "lovely-injector/crates/lovely-unix" }
pretty_env_logger = "0.5.0"
dirs = "6.0.0"
tauri-plugin-fs = "2"
log = "0.4.25"
fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs" }

[[bin]]
name = "BMM"
path = "src/main.rs"
